# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ab49ed1daaf68c3674af2a98b86474289c41178818acdbae4d7f69d5d3a07a1352cc2243687a8c5e83051d23614deb24b65b73ca46ca4c3666ec8613a09afe9

test:
  secret_key_base: 6a33301f626dc17b192e8599c8f04cc982c1d23334d578136c70bdd3fde3dce8448bf91bfb934df792ae0219e6342495dad892db32381d3ded13019d51f0baff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
